services:
  tw-user-service:
    build:
      context: ./tw-user-service
      dockerfile: Dockerfile
    container_name: tw-user-service
    restart: unless-stopped
    env_file:
      - ./tw-user-service/.env
    environment:
      - APP_ENV=local
    ports:
      - "8081:8081"
    volumes:
      - ./tw-user-service:/app
      - ~/.cache/go-build:/go
      - ~/.aws:/root/.aws
    command: ["air", "-c", ".air.toml"]
    networks:
      - app-network

  tweet-service:
    build:
      context: ./tweet-service
      dockerfile: Dockerfile
    container_name: tweet-service
    restart: unless-stopped
    env_file:
      - ./tweet-service/.env
    environment:
      - APP_ENV=local
    ports:
      - "8082:8082"
    volumes:
      - ./tweet-service:/app
      - ~/.cache/go-build:/go
      - ~/.aws:/root/.aws
    command: ["air", "-c", ".air.toml"]
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    env_file:
      - ./tw-user-service/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: