services:
  tw-user-service:
    build:
      context: ./tw-user-service
      dockerfile: Dockerfile
    container_name: tw-user-service
    restart: unless-stopped
    env_file:
      - ./tw-user-service/.env
    environment:
      - APP_ENV=local
    ports:
      - "8081:8081"
    volumes:
      - ./tw-user-service:/app
      - ~/.cache/go-build:/go
      - ~/.aws:/root/.aws
    command: ["air", "-c", ".air.toml"]
    networks:
      - app-network

  tweet-service:
    build:
      context: ./tweet-service
      dockerfile: Dockerfile
    container_name: tweet-service
    restart: unless-stopped
    env_file:
      - ./tweet-service/.env
    environment:
      - APP_ENV=local
    ports:
      - "8082:8082"
    volumes:
      - ./tweet-service:/app
      - ~/.cache/go-build:/go
      - ~/.aws:/root/.aws
    command: ["air", "-c", ".air.toml"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge